### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by KMAyman** [data301-2021-summer2/project-group46-project#1]
Hello, 

My name is Ayman and I will be giving you some feedback on your project. 

Overall, the project is a fantastic start and there are some suggestions I have that will greatly improve the quality of your project.

I have divided up the feedback into several sections so it is easier for you to implement.

## Task 1

Good work.

## Task 2

Good work.

## Task 3

I couldn't see any description of Rylan's EDA. Similar plots for both EDA's. Try to have different research questions and then either combine them as a single analysis or multiple analyses.

## Task 4
 
Good work.

**Comment by RylanRCox** [comment]
Added comments to each of my steps.

**Comment by jacobharding** [comment]
We looked over our plots for the EDA's to find similarities between them and the plots have similar styling, but the data we are plotting is different. We couldn't find a plot to change or delete since each of the plots we felt were important for both our initial EDA analyses.
